### ISSUE TITLE
README not displaying properly in User Configuration

### ISSUE THREAD

**Issue by xilopaint** [alfredapp/deep-contacts-search-workflow#1]
It might be a bug in Alfred's markdown syntax, or the lack of a scaping feature, but I'm posting here anyway.

<img width="479" alt="Screenshot 2023-03-23 at 08 39 27" src="https://user-images.githubusercontent.com/11052366/227193510-82169280-2757-4573-bb03-c27c9673fa29.png">

**Comment by vitorgalvao** [comment]
Thank you for the catch. Fixing in wording for now but making an internal note to check the parsing.
